apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  labels:
    app: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "worker"
          effect: "NoSchedule"
      containers:
      - name: jenkins-app
        image: abdelrahmangad275/jenkins-app:IMAGE_TAG
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  labels:
    app: jenkins-app
spec:
  type: ClusterIP
  selector:
    app: jenkins-app
  ports:
    - port: 80
      targetPort: 8080
